ifeq ($(strip $(AUDIO_ENABLE)), yes)
    SRC += muse.c
endif

LTO_ENABLE = yes

CONSOLE_ENABLE = no
MIDI_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

OS_DETECTION_ENABLE = yes
REPEAT_KEY_ENABLE = yes
